// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: "mysql://"+ process.env.DB_USER + ":" + process.env.DB_PASSWORD+"@"+ 
process.env.DB_HOST+":"+ process.env.DB_PORT
+"/"+ process.env.DB_NAME
 }, 
});
